# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4392a81f633f46e0ada8b0c4931b16ddc2bc3663dce02a6fb2c11918e1c10a4ed0b7fd17e74730b8a637f5ec09c4ec0e484daf21990666b16920cfba49a5d750

test:
  secret_key_base: 077e168c36ac5aef95e1d91955a8cea7bd985fad7c0df1a54408434871332b1cf10a2e538253664811491bde7178581d67dc754f0767988d1e764d8b8290f1d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
